
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - goblin-network

  goblin-backend:
    build:
      context: ./goblin_backend
      dockerfile: Dockerfile
    container_name: goblin-backend
    environment:
      - AMQP_URL=amqp://admin:admin@rabbitmq:5672/
      - AMQP_QUEUE=goblin
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - goblin-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  goblin-network:
    driver: bridge
