name = "AB"

[[steps]]
name = "modelA"
function = "modelA"
inputs = ["default_input"]
timeout = 10000

[[steps]]
name = "modelB"
function = "modelB"
inputs = ["default_input"]
timeout = 10000

[[steps]]
name = "dbInsert"
function = "dbInsert"
inputs = ["modelA", "modelB"]
timeout = 5000
